### ISSUE TITLE
Google form for user submission has been disabled

### ISSUE THREAD

**Issue by Duffadash** [davidferguson/yahoogroups-joiner#11]
It seems that the Google Form listed in step for of Prerequisites has been disabled by Google for violating their Terms of Service
![image](https://user-images.githubusercontent.com/6000413/69836966-9f70b680-124c-11ea-8663-6512ec8fe70a.png)

**Comment by andrewferguson** [comment]
We now have a new form: https://docs.google.com/forms/d/e/1FAIpQLSdh6wxiTbpmoMY-RIFXHPo3XV8gR8VqFS6tz4hhRcnpMR6esA/viewform?usp=sf_link
