### ISSUE TITLE
Verify Your Email Address

### ISSUE THREAD

**Issue by barik** [davidferguson/yahoogroups-joiner#15]
When I try to Join Group, I receive the following dialog:

![image](https://user-images.githubusercontent.com/441243/70397296-ecc7f300-19c5-11ea-8c7d-dc850c15a1c3.png)

Clicking "link your email address" takes me to a Personal Info page, but I see no further steps to actually do the linking.

**Comment by andrewferguson** [comment]
This seems to be a fairly common issue, searching for `yahoo groups "your email address is not linked to a yahoo id"` brings up various results, e.g.:

https://joshuatj.com/2018/07/18/your-email-address-is-not-linked-to-a-yahoo-id-yahoo-groups/

**Comment by barik** [comment]
Thanks, unfortunately the [Yahoo! Groups membership wizard](https://groups.yahoo.com/neo/memwiz) isn't working either. Not sure what else to try.

![image](https://user-images.githubusercontent.com/441243/70397656-fe5eca00-19c8-11ea-83c0-ec71b142f400.png)

**Comment by andrewferguson** [comment]
Uhh, not sure. Perhaps try making a new Yahoo account?

**Comment by barik** [comment]
Nope, same problem with a second new account. I'll wait for a bit to see if anyone else encounters this issue, and try again.

**Comment by mynameisfiber** [comment]
I was able to solve this by going to my [account security](https://login.yahoo.com/account/security) page and adding a fallback email address. This will be the actual email address that the group subscriptions go to. Once this is done, you should see it listed at the [wizard](https://groups.yahoo.com/neo/memwiz).

For some reason, I saw this when I chose to create a yahoo address with the new account. Also, I was unable to actually link the groups account with the yahoo email address. *shrug*

**Comment by barik** [comment]
Thanks, it looks like it does require a fallback address. Now I'm able to join groups.
