### ISSUE TITLE
Your email address is not linked to a Yahoo ID

### ISSUE THREAD

**Issue by ThatAstronautGuy** [davidferguson/yahoogroups-joiner#17]
When trying to join groups I get the message "Your email address is not linked to a Yahoo ID. To join this group, you need to link your email address to a Yahoo account."

This is a brand new account, and the membership wizard thing that showed up when I googled the error did nothing for me.

**Comment by barik** [comment]
See https://github.com/davidferguson/yahoogroups-joiner/issues/15. It looks like you need a fallback e-mail address.

**Comment by ThatAstronautGuy** [comment]
That did it, thanks! I missed it since it was in the closed issues.
