### ISSUE TITLE
hidden/missing groups stall the script

### ISSUE THREAD

**Issue by DigiTester** [davidferguson/yahoogroups-joiner#19]
I've got the "Couldn't find group in directory--click here in case it's just hidden." message, but the group appears not to exist any more and the script has stalled. When I restart it I just get that same group again, which I can't join.
https://groups.yahoo.com/neo/search?query=Homeschool_Friends_in_Iowa

**Comment by davidferguson** [comment]
Saw on IRC that this is now resolved, so closing
