### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Zopolis4** [davidferguson/yahoogroups-joiner#22]
log: 
Access to XMLHttpRequest at 'https://df58.host.cs.st-andrews.ac.uk/yahoogroups/get/' from origin 'chrome-extension://bcfnaaoffngbfhkgmpcailfahpgbanad' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)

**Comment by davidferguson** [comment]
This project ended nearly a year ago, and as such the server doesn't exist any more. Thanks for your interest though!

**Comment by Zopolis4** [comment]
oh. oops
